# Generated by Django 3.1.5 on 2021-01-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201218_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('create_customer', 'allow to create new customer'), ('update_customer', 'allow to update new customer'), ('del_customer', 'allow to delete new customer')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('list_all_products', 'allow to view all product list')]},
        ),
    ]
