# Generated by Django 3.1.5 on 2021-01-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210106_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('create_customer', 'allow to create new customer'), ('update_customer', 'allow to update new customer'), ('delete', 'allow to delete new customer')]},
        ),
    ]
