# Generated by Django 3.1.5 on 2021-02-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210106_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('create', 'allow to create new customer'), ('update', 'allow to update customer'), ('delete', 'allow to delete customer')]},
        ),
    ]
