# Generated by Django 3.1.5 on 2021-02-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210201_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
