# Generated by Django 3.1.5 on 2021-02-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210201_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': []},
        ),
    ]
