# Generated by Django 3.1.5 on 2021-02-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210201_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('create', 'allow to create new customer'), ('update', 'allow to update customer'), ('delete', 'allow to delete customer')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('list_all_products', 'allow to view all product list')]},
        ),
    ]
