# Generated by Django 3.1.5 on 2021-02-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210201_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
